# Generated by Django 5.1.2 on 2024-11-01 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadai', '0002_cart_order_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
